import type { Metadata } from "next";
import { Antonio, Anton_SC, Inter } from "next/font/google";
import "./globals.css";
import { NavBar } from "./components/NavBar";

const antonio = Antonio({
  variable: "--font-geist-sans",
  subsets: ["latin"],
  display: "swap",
});

const anton_SC = Anton_SC({
  variable: "--font-heading",
  weight: "400",
  subsets: ["latin"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-body",
});

export const metadata: Metadata = {
  title: "Tiph Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${antonio.variable} ${anton_SC.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <NavBar />
        {children}
      </body>
    </html>
  );
}
